### ISSUE TITLE
(Suggestion) Add Witcher-Compendium Git-Hub Project to core system

### ISSUE THREAD

**Issue by AlexanderTheGr3at** [Stexinator/TheWitcherTRPG#15] opened 2024-03-07 19:12 UTC
There is another project here on git-hub that has the whole of The Witcher official compendium on it. Would be great to include it into this system.

[https://github.com/Siryphas/Witcher-Compendium](https://github.com/Siryphas/Witcher-Compendium)

**Comment by Stexinator** [comment] 2024-03-13 07:24
This is to close to copyright infringement in my country to add it to my fork. If your country is more lenient we can start developing on your fork

**Comment by Godsassassin007** [comment] 2024-03-13 07:44
> This is to close to copyright infringement in my country to add it to my fork. If your country is more lenient we can start developing on your fork

I'd love to develop my own fork, I don't have nearly enough knowledge or skill for that unfortunately. Luckily the author of it sent a copy to RTG and they seemed to support it so I don't think any copyright issues would be a challenge.

![Screenshot_20240313_034258_Firefox](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/350c4714-da9c-4489-9b2c-dff786b52054)

**Comment by Godsassassin007** [comment] 2024-03-13 07:55
> This is to close to copyright infringement in my country to add it to my fork. If your country is more lenient we can start developing on your fork

I created my own fork. I love it if you helped with it. And I'll start learning myself how to code with JavaScript so I can be of use.

**Comment by Stexinator** [comment] 2024-03-13 08:07
> > This is to close to copyright infringement in my country to add it to my fork. If your country is more lenient we can start developing on your fork
> 
> I'd love to develop my own fork, I don't have nearly enough knowledge or skill for that unfortunately. Luckily the author of it sent a copy to RTG and they seemed to support it so I don't think any copyright issues would be a challenge.
> 
> ![Screenshot_20240313_034258_Firefox](https://private-user-images.githubusercontent.com/59134326/312354117-350c4714-da9c-4489-9b2c-dff786b52054.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTc0NDUsIm5iZiI6MTcxMDMxNzE0NSwicGF0aCI6Ii81OTEzNDMyNi8zMTIzNTQxMTctMzUwYzQ3MTQtZGE5Yy00NDg5LTliMmMtZGZmNzg2YjUyMDU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYTI5YjhkZDE2NDA0NzNkZWQxNDA0NzcxMjRlYmRjOTg5NWU5M2YyZGQ0YTdiMjBiYWE2MWY0YmY0YTBmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dCjAYmajs0Z01YNOAvKkqyN50rLAR4sgkPAfek1AdtE)

This is great. But this only applies to Siryphas and usually this things are not transferable. Can you ask him to make a fork? He is allowed to incorporate the compendium according to your message. Then we can do all the improvements on his fork and get the good stuff of all worlds :)

**Comment by Godsassassin007** [comment] 2024-03-13 08:15
> > > This is to close to copyright infringement in my country to add it to my fork. If your country is more lenient we can start developing on your fork
> > 
> > 
> > I'd love to develop my own fork, I don't have nearly enough knowledge or skill for that unfortunately. Luckily the author of it sent a copy to RTG and they seemed to support it so I don't think any copyright issues would be a challenge.
> > ![Screenshot_20240313_034258_Firefox](https://private-user-images.githubusercontent.com/59134326/312354117-350c4714-da9c-4489-9b2c-dff786b52054.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTc0NDUsIm5iZiI6MTcxMDMxNzE0NSwicGF0aCI6Ii81OTEzNDMyNi8zMTIzNTQxMTctMzUwYzQ3MTQtZGE5Yy00NDg5LTliMmMtZGZmNzg2YjUyMDU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhYTI5YjhkZDE2NDA0NzNkZWQxNDA0NzcxMjRlYmRjOTg5NWU5M2YyZGQ0YTdiMjBiYWE2MWY0YmY0YTBmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dCjAYmajs0Z01YNOAvKkqyN50rLAR4sgkPAfek1AdtE)
> 
> This is great. But this only applies to Siryphas and usually this things are not transferable. Can you ask him to make a fork? He is allowed to incorporate the compendium according to your message. Then we can do all the improvements on his fork and get the good stuff of all worlds :)

Unfortunately it looks like he hasn't been very active in months so I may not be able to get ahold of him. I did make my own fork off of yours though and am willing to take the chance if that works for you.

**Comment by Stexinator** [comment] 2024-03-13 08:23
I actually found some public information: https://rtalsoriangames.com/homebrew-content-policy/ The compendium should fulfill most of these points. Can you comb it to check if it fits the constraints?

**Comment by Godsassassin007** [comment] 2024-03-13 08:35
I think it does fit all of those. I think even the beastiary might as it isn't a full 1:1 reproduction of the state block. Like I said above though I'm more than happy to be the owner of the fork this goes on if you're worried about copyright infringement issues. I'll even reach out to RTG to get their blessings.

**Comment by Godsassassin007** [comment] 2024-03-14 00:10
> I actually found some public information: https://rtalsoriangames.com/homebrew-content-policy/ The compendium should fulfill most of these points. Can you comb it to check if it fits the constraints? I think e.g. the bestiary is off limits

It seems they're kinda okay with it. They said they can't legally permit due to the difficult licensing with the Witcher but they aren't going to hunt down or stop projects from being made.

![Screenshot_20240313_200749_Messenger](https://github.com/Stexinator/TheWitcherTRPG/assets/59134326/5bccece6-323b-41d5-97bb-db59cd70ca24)

**Comment by Stexinator** [comment] 2024-03-15 07:58
Siryas will send me an updated compendium soon that will be integrated. If you already want to see to some homebrew content I can create a module for that

**Comment by Godsassassin007** [comment] 2024-03-15 08:01
> Siryas will send me an updated compendium soon that will be integrated. If you already want to see to some homebrew content I can create a module for that

That is fantastic news! And I'm always open to new modules if you're willing. Thanks for putting all the time and effort you are into this. Means a lot to me and my group.

**Comment by Stexinator** [comment] 2024-03-15 10:33
I have created https://github.com/Stexinator/TheWitcherTRPGHomebrewRepository for homebrew stuff. Feel free to add content there

**Comment by AlexanderTheGr3at** [comment] 2024-03-15 19:27
> I have created https://github.com/Stexinator/TheWitcherTRPGHomebrewRepository for homebrew stuff. Feel free to add content there

Fantastic, thanks.

Ps: I changed my username from Godsassassin007 now that I'm actually using GitHub aha.

**Comment by Siryphas** [comment] 2024-03-16 20:31
As was already mentioned, I'm working on an updated version of the Compendium, then I will combine it with the System Module

**Comment by AlexanderTheGr3at** [comment] 2024-03-16 20:49
> As was already mentioned, I'm working on an updated version of the Compendium, then I will combine it with the System Module

I love you guys! I'm group is going to be so excited! I can't wait to learn some coding so I can give back.

**Comment by Melkkart** [comment] 2024-03-26 21:30
I would love to help, I have everything created in Spanish, rules, monsters, descriptions, etc., but unfortunately, translators are reluctant to freely share such information, they did not want their translation to be shared on VTT.

**Comment by AlexanderTheGr3at** [comment] 2024-03-26 21:52
> I would love to help, I have everything created in Spanish, rules, monsters, descriptions, etc., but unfortunately, translators are reluctant to freely share such information, they did not want their translation to be shared on VTT.

@Siryphas has actually made a great one that we are just waiting to implement into the system.

**Comment by Siryphas** [comment] 2024-03-27 03:55
> I would love to help, I have everything created in Spanish, rules, monsters, descriptions, etc., but unfortunately, translators are reluctant to freely share such information, they did not want their translation to be shared on VTT.

I have it all done, but I'm more than happy to give you full permissions to translate anything and everything in the compendium for use in your language(s).

**Closed** 2024-03-27 20:44 UTC
