### ISSUE TITLE
Investigation System

### ISSUE THREAD

**Issue by Siryphas** [Stexinator/TheWitcherTRPG#67] opened 2024-04-30 18:18 UTC
I know it might be a pain, but seeing as how we have a **Verbal Combat** mechanic in the system, I thought maybe we could see the implementation of the **Investigation** mechanic as well. It would be helpful to have PCs able to roll evidence checks and have a sheet to keep track of the Mystery's Complexity, roll damage against it, etc.
_A Witcher's Journal_, pages: 145-153

**Comment by Stexinator** [comment] 2024-05-05 11:40
@moliloo this can be tested at
https://github.com/Stexinator/TheWitcherTRPG/tree/feature/investigation_sheet

Thanks for testing

**Comment by Stexinator** [comment] 2024-05-08 13:38
I will release it end of week. Due to it not impacting existing things the risk should be very small.

**Comment by moliloo** [comment] 2024-05-11 18:44
## Tests
### Clues and Obstacles Items
#### Feature Working
- Creating the items and they are saved
- Drag to the investigation sheet and information been there
#### Bugs
- `skillsUsed` input dont work when i drag the item to the sheet, i need select the option inside the sheet

### Investigation Sheet
#### Feature Working
- Creat items in the sheet works well
- Hide option when activate, don't show the clue or obstacle to other permissions, only by the owner
- Others permissions can't edit the inputs, both items, and the sheet information (Name, difficulty, complexity etc)
#### Bugs
- When other player isn't the owner and click in the some skill in `Skill used`, the skill is desapear and a error appears in console

| Before Click | After Click | Error in Console | Error in Foundry |
|--------|--------|--------|--------|
| ![](https://media.discordapp.net/attachments/725195811096363090/1238923236025045172/image.png?ex=66410cad&is=663fbb2d&hm=fa569b3f0c46402f02035d0ef69ec32576627bdbcba579adfeb6919d1058709a&=&format=webp&quality=lossless) | ![](https://media.discordapp.net/attachments/725195811096363090/1238923312424292403/image.png?ex=66410cbf&is=663fbb3f&hm=0959c419efccad2471222fb29119e59dc5767983f3c0f573a7d7c2dedd064b11&=&format=webp&quality=lossless) | ![](https://media.discordapp.net/attachments/725195811096363090/1238923357034909788/image.png?ex=66410cca&is=663fbb4a&hm=4ea8f4d3a5e978f05b9f8cd4776e7d91215a8f532300d8253f8bf75eb9b15939&=&format=webp&quality=lossless) | ![](https://media.discordapp.net/attachments/725195811096363090/1238923397073993769/image.png?ex=66410cd3&is=663fbb53&hm=f6e07b02b0363a1f962471f72508e5b397f7aa37c069a388462bf746e5817f49&=&format=webp&quality=lossless) |

**Comment by Stexinator** [comment] 2024-05-12 09:03
`Bugs

    When other player isn't the owner and click in the some skill in Skill used, the skill is desapear and a error appears in console
`

I cannot reproduce it. When the player is observer everything is disabled as expected and when he is owner he can modify it. Can you check if additional steps are necessary? Everything else is fixed and on the dev branch

**Comment by moliloo** [comment] 2024-05-12 15:21
I downloaded the dev branch again and the dame thing happens, i create 2 player users, for one i give the observer permission to the sheet, the other, i give the limited permisison to the mystery sheet, then i log in this accounts oppening the sheet, when i click in the name of some skill, for example `Awareness X`, this error appears to me, but if i close and open the sheet again, `Awareness X` is there again

**Comment by Stexinator** [comment] 2024-05-12 17:27
Okay I can reproduce it. But that is a foundry native element so I think I cannot do anything about it. I queried people about it if this behaviour can be avoided. Hence its not breaking functionality (the data is not permanently changed) I will go forward with releasing :) If I get a solution or an official statement I will post it here

**Comment by Stexinator** [comment] 2024-05-12 17:34
Well, that was fast. It seems to be unexpected behaviour but it probably will not be fixed in v11

**Closed** 2024-05-12 17:41 UTC
Labels: feature, beta test
